name: Update Tailscale Submodule

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 时间每天零点
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写入权限来创建提交和标签
      pull-requests: write  # 如果需要创建 PR，则需要此权限

    outputs:
      new_tag_created: ${{ steps.check-tags.outputs.new_tag }}
      tag_version: ${{ steps.check-tags.outputs.tag_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check for new Tailscale tags
        id: check-tags
        run: |
          # 获取 submodule 最新的 tag
          cd tailscale
          git fetch --tags origin
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          cd ..

          # 检查当前仓库是否已经有这个 tag
          if git rev-parse "$LATEST_TAG" >/dev/null 2>&1; then
            echo "Tag $LATEST_TAG already exists in current repository"
          else
            echo "new_tag=true" >> $GITHUB_OUTPUT
            echo "tag_version=$LATEST_TAG" >> $GITHUB_OUTPUT
          fi

      # 直接推送到主分支的版本
      - name: Update submodule
        if: steps.check-tags.outputs.new_tag == 'true'
        run: |
          cd tailscale
          git checkout ${{ steps.check-tags.outputs.tag_version }}
          cd ..
          git add tailscale
          git commit -m "chore: update tailscale submodule to ${{ steps.check-tags.outputs.tag_version }}"
          git tag ${{ steps.check-tags.outputs.tag_version }}
          git push origin main --tags

  trigger-build:
    needs: update-submodule
    if: needs.update-submodule.outputs.new_tag_created == 'true'
    uses: ./.github/workflows/build-docker.yml
    with:
      tag_version: ${{ needs.update-submodule.outputs.tag_version }}
